# Configuration file that defines the fetched data


# Configure the destinations (outputs)
destinations:
  
  # Print to console
  console:
    type: console

  # InfluxDB Storage
  influxdb1:
    type: influxdb
    url: influxdb
    port: 8086
    token: someToken
    defaultBucket: someBucketToUse

  # Victoria Metrics
  victoria-metrics:
    type: victoriaMetrics
    options:
      url: 

logLevel: debug

# Scraping jobs
jobs:
  myJob: # Job Name
    schedule:
      # interval: 24h
      cron: "* * * * *"

    # What to scrape
    input:
      # Define the HTTP request details
      request:
        url: <url to fetch>
        method: get  # Optional, defaults to 'get'
        headers:     # Optional
          User-Agent: "Mozilla/5.0"
          Accept: "text/html"
        # data:      # Optional, for POST/PUT requests
        #   key: value
      
      # Use a json or yaml file as template
      template: "templateFile.json"

      # With embedded template
      # template:
      #   myValue: h1
      #   mySecondValue: "#123"

    outputs:
      - to: influxdb1 # Defined in destinations
        tags:         # Tags to apply
          job: myJob  # Tag values MUST be string
        fields:       # Fields to apply
          myField: 123  # Field values can be floats or strings
          myStringField: hello world
        transform: # Transformations that can be applied on the data
          # Convert the type to float
          - target: myValue
            type: float

